global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: tgi-server
    static_configs:
      - targets: ['10.0.12.75:8080']

  - job_name: dcgm-exporter
    static_configs:
      - targets: ['10.0.12.75:9400']

  - job_name: node-exporter
    static_configs:
      - targets: ['10.0.12.75:9100']