# Currently not running `terraform plan` or `terraform apply` because this repo is public
# Ideally there'd be two workflows, one for plan (on PR) and one for apply (on merge)
name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/terraform.yml'
      - 'infra/terraform/**.tf'

env:
  TF_VERSION: 1.10.4

jobs:
  tf:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: init
        run: terraform init -no-color -input=false

      - name: Terraform Validate
        run: terraform validate -no-color