name: Terraform Plan

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/terraform-plan.yml'
      - 'infra/terraform/**.tf'

env:
  TF_VERSION: 1.10.4
  AWS_REGION: us-east-1


permissions: # outside or inside of the job?
  id-token: write
  contents: read
  pull-requests: write

jobs:
  tf-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v # what version?
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: terraform-plan-${{ github.run_id }} # do i need session name? what about run_id?
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3 # what version?
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false # do i need wrapper?

      - name: Terraform Format Check
        run: terraform fmt -check -recursive # do i need recursive?
        continue-on-error: true # what is this for?

      - name: Terraform Init
        id: init
        run: terraform init -no-color -input=false # what is input?

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color -input=false -out=tfplan
        continue-on-error: true

      # Generate Plan Summary?
      - name: Add plan
        uses: actions/github-script@v7
        with:
          script: |
            # add plan to PR as a comment; try not to double post? or double post? make it simple
      - name: Terraform plan status
        if: steps.plan.outcome == 'failure' || steps.plan.outcomes.exitcode == '1' # is this valid
        run: exit 1