apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dcgm-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/dcgm-exporter/helm-charts
    chart: dcgm-exporter
    targetRevision: 4.6.0
    helm:
      values: |
        nodeSelector:
          nvidia.com/gpu: "true"
        tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        serviceMonitor:
          enabled: true
        hostPID: true
        hostNetwork: true
        securityContext:
          privileged: true
        extraHostVolumes:
        - name: nvidia-toolkit
          hostPath: /usr/local/nvidia/toolkit
        extraVolumeMounts:
        - name: nvidia-toolkit
          mountPath: /usr/local/nvidia/toolkit
          readOnly: true
        env:
        - name: LD_LIBRARY_PATH
          value: "/usr/local/nvidia/toolkit:$(LD_LIBRARY_PATH)"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true